### ISSUE TITLE
Should we be teaching python 3 instead of 2?

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/python-ecology#12]
There's a thread on SWC discuss about teaching Python 2 or 3. As these are people new to Python, so without history with the language, should we start them out with Python 3 and be teaching Python 3 instead of 2.x?

**Comment by ethanwhite** [comment]
+1 for Python 3 (I've been campaigning for it for a while at SWC and am happy to see that this is looking possible both their and here).

**Comment by mkuzak** [comment]
+ 1 for Python 3. I made a pull request in case we agree on it.
