### ISSUE TITLE
use the portal data from FigShare for this lesson

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/python-ecology#23]
This lesson uses the portal data, but a copy that is in the repo, rather than the one on FigShare

https://figshare.com/articles/Portal_Project_Teaching_Database/1314459

It would be good to update the lesson to use this data. This will likely require some changes throughout the lesson though, since the FigShare version of surveys.csv has an added column 'hindfoot_length' and different column headers.

**Comment by mkuzak** [comment]
I'm working on adjusting this lesson to FigShare version of the data. In 04-merging-data `survey2001.csv` and `survey2002.csv` are used, from local data directory. Those files are not available on FigShare. Should we keep it like it is or add those files to FigShare?
