### ISSUE TITLE
loc vs iloc clarification please :) 

### ISSUE THREAD

**Issue by lwasser** [datacarpentry/python-ecology#7]
hey @qjcg et all... i am working through some of the materials again. the loc vs iloc text is pretty confusing and i'm trying to figure out a simple way to explain it. it seems loc accepts labels and numeric integer ranges. Iloc does not accept labels. But otherwise what is the difference? is it just labels vs no labels?

http://lwasser.github.io/python-ecology/02-index-slice-subset

Can you please have a look and help me clarify the difference so i can succinctly convey this at the workshop? thank you!
--------------------------------------------------------------------------
We can select specific ranges of our data in both the row and column directions using the loc and iloc arguments. The loc argument allows you to select data using labels AND numeric integer locations. Put another way, loc only accepts integer index values. iloc only allows you to select ranges using labels.

NOTE: Index values and labels must be found in the DataFrame or you will get a KeyError. Remember that the start bound and the stop bound are included. When using loc Integers can be used, but they refer to the index label and not the position. Thus when you use loc, and select 1:4, you will get a different result than using iloc to select rows 1:4.

To select a subset of rows AND columns from our DataFrame, we can use the iloc method. For example, we can select month, day and year (columns 2, 3 and 4 if we start counting at 1), like this:

--------------------

**Comment by qjcg** [comment]
>  is it just labels vs no labels?

Yes (see [this summary](http://pandas.pydata.org/pandas-docs/version/0.16.0/indexing.html#different-choices-for-indexing)).

- `loc`: indexing via *labels* ([ref](http://pandas.pydata.org/pandas-docs/version/0.16.0/indexing.html#indexing-label))
- `iloc`: indexing via *integers* (that's what the "i" stands for) ([ref](http://pandas.pydata.org/pandas-docs/version/0.16.0/indexing.html#indexing-integer))

> The loc argument allows you to select data using labels AND numeric integer locations. 

NO.

> Put another way, loc only accepts integer index values. iloc only allows you to select ranges using labels.

This is backwards! Disappointed that I didn't catch this earlier.

I'll send a PR ASAP.

**Comment by lwasser** [comment]
cool - i thought that was mixed up! Thank you. i've made a few changes on my repo to that file that aren't on DC yet. Can you PR to my repo when you make the edits and then i'll PR to DC later today??

Leah

**Comment by qjcg** [comment]
> Can you PR to my repo when you make the edits and then i'll PR to DC later today??

Will do!

**Comment by lwasser** [comment]
Awesome! thanks!!! :)

**Comment by mkuzak** [comment]
I think that issue is resolved now and should be closed.

**Comment by qjcg** [comment]
@mkuzak: agreed. @tracykteal, as I don't have the permissions necessary for this, can you please do the honors?
